const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
test('live board filters log availability and separates PAN from player lists',()=>{
 const hidden=new Set([8,17,26]), widths={},writes=[],calls=[],formulas=[],ruleCalls=[],formats=[];
 const range=new Proxy({}, {get:(_,name)=>(...args)=>{calls.push(name);return range;}});
 const sheet=new Proxy({}, {get:(_,name)=>{
   if(name==='getMaxRows')return ()=>1000;
   if(name==='getMaxColumns')return ()=>26;
   if(name==='getRange')return (...args)=>new Proxy({}, {get:(_,method)=>method==='_range'?args:(...values)=>{if(method==='setValues')writes.push({args,values:values[0]});if(method==='setFormula')formulas.push(values[0]);if(method==='setFormulas')formulas.push(...values[0].flat());if(method==='setNumberFormat')formats.push({args,format:values[0]});return range;}});
   if(name==='showColumns')return ()=>hidden.clear();
   if(name==='hideColumns')return (col,n=1)=>{for(let i=0;i<n;i++)hidden.add(col+i);};
   if(name==='setColumnWidth')return (col,w)=>{calls.push('setColumnWidth');widths[col]=w;};
   if(name==='setColumnWidths')return (col,n,w)=>{for(let i=0;i<n;i++)widths[col+i]=w;};
   return ()=>sheet;
 }});
 const rule=new Proxy({}, {get:(_,name)=>(...args)=>{ruleCalls.push([name,...args]);return name==='build'?{}:rule;}});
 const ctx={CacheService:{getDocumentCache:()=>({put:()=>{}})},SpreadsheetApp:{getActive:()=>({getSheetByName:()=>sheet}),newConditionalFormatRule:()=>rule,InterpolationType:{NUMBER:'number',PERCENTILE:'percentile'},BorderStyle:{SOLID:'solid'},WrapStrategy:{CLIP:'clip'}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('apps-script/Engine.gs','utf8')+'\n'+fs.readFileSync('apps-script/Code.gs','utf8')+'\n'+fs.readFileSync('apps-script/Live.gs','utf8')+'\n'+fs.readFileSync('apps-script/Pan.gs','utf8'),ctx);
 ctx.showReplacementLevels_=()=>{};ctx.table_=()=>sheet;ctx.buildPanFormulas_=()=>calls.push("buildPanFormulas");
 ctx.evaluate=()=>({available:['F','D','G'].map(g=>({group:g,id:g,name:g,points:100,par:20,adp:5,pan:null,pos:g,team:'TOR'})),panReady:false});
 ctx.renderBoard_({c:{teams:12,rounds:16,parTop:.02,panTop:.02,adpBottom:.1,highlightCount:12,espnRankWeight:.2,domRankWeight:.4},players:[{},{},{}],state:{current:1,next:24,removed:new Set()}});
 assert.ok(ruleCalls.some(r=>r[0]==='setGradientMaxpointWithValue'&&r[1]==='#ffffff'&&r[2]==='percentile'));
 assert.equal(ruleCalls.filter(r=>r[0]==='setGradientMinpointWithValue'&&r[1]==='#ffffff'&&r[2]==='percentile'&&r[3]==='98').length,2);
 assert.ok(!ruleCalls.some(r=>r[0]==='whenNumberLessThanOrEqualTo'));
 assert.ok(ruleCalls.some(r=>r[0]==='setGradientMinpoint'&&r[1]==='#f4cccc'));
 const teamRules=ruleCalls.filter(r=>r[0]==='whenFormulaSatisfied'&&r[1].includes('Targets!')&&(r[1].includes('Targets!E2:E')||r[1].includes('Targets!F2:F')));
 assert.equal(teamRules.length,6);
 assert.deepEqual(teamRules.map(r=>r[1].match(/Targets!([EF])2/)[1]),['F','E','F','E','F','E']);
 assert.deepEqual([...hidden].sort((a,b)=>a-b),[5,6,7,8,13,16,19,20,21,22,27,30,33,34,35,36,41]);
 assert.equal(Object.entries(widths).reduce((sum,[col,w])=>sum+(hidden.has(Number(col))?0:w),0),1182);
 assert.ok(formulas.some(f=>f.includes("'Projection Comparison'!F$3:F$")));
 const coefFormulas=formulas.filter(f=>f.includes("'Projection Comparison'!F$3:F$"));
 assert.equal(coefFormulas.length,3);
 assert.deepEqual(coefFormulas.map(f=>Number(f.match(/<=([25])/)[1])),[5,5,2]);
 assert.ok(coefFormulas.every(f=>f.includes("'Projection Comparison'!H$3:H$")));
 assert.deepEqual(formats.filter(x=>x.format==='0%').map(x=>x.args[1]),[10,24,38]);
 assert.ok(ruleCalls.filter(r=>r[0]==='setRanges').flatMap(r=>r[1]).every(r=>![10,24,38].includes(r._range[1])));
 assert.equal(formulas.filter(f=>f.startsWith('=IFNA(SORT(FILTER')).length,3);
 assert.ok(!formulas.some(f=>f.includes('FH_STATE')));
 assert.ok(formulas.some(f=>f.startsWith('=COUNTA(\'Draft Log\'!A2:A1000)+1')));
 assert.ok(formulas.some(f=>f.includes('XLOOKUP("panGap"')));
 assert.ok(calls.includes('buildPanFormulas'));
 assert.ok(!formulas.some(f=>f.includes('FH_PAN')));
 assert.ok(formulas.filter(f=>f.startsWith('=IFNA(SORT(FILTER')).every(f=>f.includes('HSTACK(')&&f.includes('!T2:T')&&f.includes('),11,FALSE,9,TRUE')));
 assert.ok(writes.filter(w=>w.args[0]===3).every(w=>w.values[0][3]==='Age'&&w.values[0][4]==='espn'&&w.values[0][5]==='ADP'&&w.values[0][6]==='Dom'&&w.values[0][7]==='sADP'&&w.values[0][8]==='sRk'&&w.values[0][9]==='coefV'&&w.values[0][11]==='PAN'));
});
